osc=no
deinterlace=auto
autofit=50%
scale=spline36
scale-antiring=0
dscale=bilinear
dscale-antiring=0
cscale=spline36
cscale-antiring=0
deband=no
correct-downscaling=yes
linear-downscaling=no
sigmoid-upscaling=yes
target-colorspace-hint=yes
target-peak=400
hdr-compute-peak=yes
inverse-tone-mapping=no
tone-mapping=auto
tone-mapping-param=0.3 # assume spline
saturation=0
hdr-peak-percentile=99.0
gpu-max-shader-storage=64
gpu-shader-cache=4
hwdec-extra-frames=4