//! Stage 3: Windows Shell API extraction
//!
//! Uses IThumbnailCache with WTS_EXTRACTDONOTCACHE so thumbnails generated by
//! this app are persisted only in the app-owned cache, not Explorer's cache.

use std::path::Path;

/// Extract thumbnail using Windows Shell API
///
/// This is the universal fallback that works for most file types without
/// populating the Windows Explorer thumbnail cache.
pub fn extract(path: &Path) -> Result<(Vec<u8>, u32, u32), Box<dyn std::error::Error>> {
    extract_with_size(path, None)
}

pub fn extract_with_size(
    path: &Path,
    requested_size: Option<u32>,
) -> Result<(Vec<u8>, u32, u32), Box<dyn std::error::Error>> {
    crate::infrastructure::windows::icons::extract_thumbnail_without_windows_cache_with_size(
        path,
        requested_size,
    )
}
